<?php
// $Id$
/**
* @file
* Module for fetching data from Goodreads.com
* This module provides block content retrieved from 
* Goodreads.com bookshelf.
* @see http://www.goodreads.com
*/

function goodreads_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
		case 'list':
		$blocks[0]['info'] = t('Goodreads Bookshelf');
		return $blocks;
		case 'view':
		$blocks['subject'] = t('On the Bookshelf');
		$blocks['content '] = t('Temporary content');
		return $blocks;
	}
}