# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 30 Nov 2010 21:12:06 +0000
*               @ALL          0
*               @user         8
