<?php
// $Id: content.module,v 1.301.2.120 2010/08/11 23:27:10 pwolanin Exp $
/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */

function bcnav_autoload($cn) {
	$fn = $_SERVER['DOCUMENT_ROOT']."/lib/php/class.$cn.php";
	if(is_file($fn)) {
		require_once($fn);
	}
}
spl_autoload_register("bcnav_autoload");

/**
 * @todo handle things on node_delete
 */

function bcnav_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	if($op == "update") {
		if(ereg('^bewertung_(.*)$', $node->type)) {
			$v = BCVotings::byRatingNode($node);
			$v->reindex();
		}
	} elseif($op == "delete") {
		if(ereg('^bewertung_(.*)$', $node->type)) {
			$v = BCVotings::byRatingNode($node);
			$v->reindex();
		}
		/**
		 * Er muss bei produkten
		 * * alle abos löschen
		 * * alle Votings löschen
		 * * alle gespeicherten werte (History) löschen
		 * * Index löschen
		 *
		 * er muss bei Banken
		 * * den Index löschen
		 * * für alle Produkte der Bank das o.g. tun
		 */

		//*
		//Alle Abos löschen
		//*
	}
}

function bcnav_menu() {
  $items = array();
  $items['admin/content/import'] = array(
    'title' => 'Data import',
    'page callback' => 'bcnav_import',
  	'access callback' => 'bcnav_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/bcsend'] = array(
    'title' => t('Sends out as BankingCheck-Newsletter'),
    'page callback' => 'bcnav_nodesender_dialog',
  	'access callback' => 'bcnav_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/import/dataimport'] = array(
    'title' => 'Produktimport',
    'page callback' => 'bcnav_import',
  	'access callback' => 'bcnav_access',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/content/import/bankimport'] = array(
    'title' => 'Bankenimport',
    'page callback' => 'bcnav_import_bankonly',
  	'access callback' => 'bcnav_access',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
/**
  * Check whether to display "my tab".
  */
function _bcnav_check_tab_permission($node) {
  if ($node->type == 'productitem') {
    return TRUE;
  } else {
    return FALSE;
  }
}
function bcnav_import_bankonly() {
	$main = new BCImport();
	if($_GET["refresh"]=="true") {
		$main->updateSrc();
	} elseif($_GET["import"]!="") {
		$main->doImportBankByFeed($_GET["import"]);
	}
	echo theme(
		"page",
		_bcnav_importHeader()." ".$main->getBankImportList()
	);

}
function bcnav_node_operations() {
	$operations = array(
    	'bcnav_node_operations' => array(
      		'label' => t('Sends out as BankingCheck-Newsletter'),
      		'callback' => 'bcnav_nodesender',
    	),
    );
	return $operations;
}
//function bcnav_form_alter(&$form, &$form_state, $form_id) {
//	switch($form_id) {
//		case "bewertung_tagesgeld_node_form":
//			break;
//	}
//}
function bcnav_nodesender($arg) {
	drupal_goto("admin/content/bcsend", $arg);
}
function bcnav_nodesender_dialog() {
	$nids = array();
	foreach($_GET as $k=>$v) {
		if(is_numeric($k)) {
			$nids[] = $v;
		}
	}
	if(count($nids)==0) {
		$content = "Sie haben keine News zum Versenden ausgewählt,
bitte wählen Sie <a href='/admin/content/node?title=&type[]=story&promote=All&status=All&sticky=All'>hier</a> die Nachrichten aus und verwenden Sie
Bulk-Operations zum Versenden";
	} else {
		$test = new BCNodeSender($nids);
		if(array_key_exists("send", $_GET)) {
			$test->send();
		} else {
			if(array_key_exists("sendOnlyTo", $_GET)) {
				$test->send($_GET["sendOnlyTo"]);
			}
			$content = $test->preview();
		}
	}
	echo theme("page", $content);
}
function bcnav_cron() {
	$overallStartTime = microtime(true);
	$main = new BCImport();
	$main->updateSrc();
	$mails = new BCAlertSender();
	$mails->cron();
	$timeLimit = 1.0;
	$overAllTime = microtime(true)-$overallStartTime;
	if (microtime(true)-$overallStartTime>$timeLimit) {
		watchdog('BCNav', 'BCNav took longer than '.$timeLimit.' seconds: '.$overAllTime, array(), WATCHDOG_WARNING);
	}
}
function bcnav_import() {
	$main = new BCImport();

	if($_SERVER['REQUEST_METHOD']=="POST") {
		$main->doImport($_POST["ids"]);
	} elseif($_GET["refresh"]=="true") {
		$main->updateSrc();
		$mails = new BCAlertSender();
		$mails->cron();
	}
	$table = new CSV();
	$table->setDataMaxHeader($main->getImportsTable());
	echo theme(
		"page",
		_bcnav_importHeader().
		BCImport::wrap(
			'<input value="ausgewählte Produkte nach Drupal importieren" type="submit"/>'.$table->toString().'<input value="ausgewählte Produkte nach Drupal importieren" type="submit"/>',
			"form",
			array(
				"action"=>"/admin/content/import/dataimport",
				"method"=>"post"
			)
		)
	);
}
function _bcnav_importHeader() {
	return 	BCImport::wrap(BCImport::getCacheFileStatsAndUpdateIfOlderThan(), "div").
		BCImport::wrap(" » Neuer Download von FinanceAdds", "a", array("href"=>"?refresh=true","style"=>"font-size:10px;padding-left:20px;padding-bottom:50px;")).
		BCImport::wrap("", "br");
}
function bcnav_access() {
	return true;
}
