<?php

$kunden=array(
  "687" => "http://www.bankingcheck.de/produkte/mietkaution/eurokaution-easykaution",
  "786" => "http://www.bankingcheck.de/produkte/kreditkarte/payango-essence-visa-prepaid-card",
  "934" => "http://www.bankingcheck.de/produkte/mietkaution/eurokaution-businesskaution",
  "935" => "http://www.bankingcheck.de/produkte/mietkaution/eurokaution-studikaution",
  "10163" => "http://www.bankingcheck.de/banken/vitrade",
  "10277" => "http://www.bankingcheck.de/banken/lynx-broker",
  "10604" => "http://www.bankingcheck.de/banken/weltsparen",
  "10667" => "http://www.bankingcheck.de/banken/benk",
  "10668" => "http://www.bankingcheck.de/banken/zinspilot"
	);

?>
